export default async function handler(req, res) {
    if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

    const { html, brandName } = req.body;
    if (!html) return res.status(400).json({ error: "Missing HTML content" });

    const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
    const VERCEL_TOKEN = process.env.VERCEL_TOKEN;

    if (!GITHUB_TOKEN || !VERCEL_TOKEN) {
        return res.status(500).json({ error: "Deployment API tokens (GitHub/Vercel) are not configured on the server." });
    }

    try {
        // Generate unique names
        const timestamp = Date.now();
        const safeName = (brandName || "site").toLowerCase().replace(/[^a-z0-9-]/g, "");
        const repoName = `brandcraft-${safeName}-${timestamp}`;
        const vercelProjectName = repoName.substring(0, 52); // Vercel max project name length is 52

        // 1. Create GitHub Repository
        const ghRepoRes = await fetch("https://api.github.com/user/repos", {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${GITHUB_TOKEN}`,
                "Content-Type": "application/json",
                "User-Agent": "BrandCraft-Deployer"
            },
            body: JSON.stringify({
                name: repoName,
                description: `Website for ${brandName} generated by BrandCraft AI`,
                private: false,
                auto_init: true
            })
        });

        if (!ghRepoRes.ok) {
            const err = await ghRepoRes.json();
            throw new Error(`GitHub Repo Creation Failed: ${err.message}`);
        }

        const repoData = await ghRepoRes.json();
        const owner = repoData.owner.login;

        // 2. Upload index.html to GitHub
        const contentEncoded = Buffer.from(html).toString("base64");
        const ghFileRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/contents/index.html`, {
            method: "PUT",
            headers: {
                "Authorization": `Bearer ${GITHUB_TOKEN}`,
                "Content-Type": "application/json",
                "User-Agent": "BrandCraft-Deployer"
            },
            body: JSON.stringify({
                message: "Deploy initial HTML from BrandCraft",
                content: contentEncoded
            })
        });

        if (!ghFileRes.ok) {
            const err = await ghFileRes.json();
            throw new Error(`GitHub File Upload Failed: ${err.message}`);
        }

        // 3. Trigger Vercel Deployment
        // We use the direct file upload approach via Vercel API for instant reliability
        const vercelRes = await fetch("https://api.vercel.com/v13/deployments", {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${VERCEL_TOKEN}`,
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                name: vercelProjectName,
                files: [
                    { file: "index.html", data: html }
                ],
                target: "production",
                projectSettings: { framework: null }
            })
        });

        if (!vercelRes.ok) {
            const err = await vercelRes.json();
            throw new Error(`Vercel Deployment Failed: ${err.error?.message || "Unknown error"}`);
        }

        const vercelData = await vercelRes.json();

        return res.status(200).json({ url: `https://${vercelData.url}`, githubUrl: repoData.html_url, deploymentId: vercelData.id, status: "success" });
    } catch (error) {
        console.error("Deployment Error:", error);
        return res.status(500).json({ error: error.message });
    }
}